---

version: '3'

networks:
  tomdo: {}

services:
  date:
    image: tomdo/date
    networks:
      tomdo: {}
  time:
    image: tomdo/time
    networks:
      tomdo: {}
  web:
    image: tomdo/web
    ports:
      - 7000:7000
    networks:
      tomdo: {}
    environment:
      DATEENDPOINT: date:7001
      TIMEENDPOINT: time:7002
