---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: date
  labels:
    app: date
spec:
  replicas: 3
  selector:
    matchLabels:
      app: date
  template:
    metadata:
      labels:
        app: date
    spec:
      containers:
      - name: date
        image: datetimeweb/date:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "7001"
        ports:
        - containerPort: 7001


---

apiVersion: v1
kind: Service
metadata:
  name: date
spec:
  selector:
    app: date
  ports:
  - name: date
    protocol: TCP
    port: 7001
    targetPort: 7001
  type: ClusterIP
