---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: server:5000/datetimeweb/web:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: PORT
          value: "7000"
        - name: DATEENDPOINT
          value: "_date._tcp.date.default.svc.cluster.local:7001"
        - name: TIMEENDPOINT
          value: "_time._tcp.time.default.svc.cluster.local:7002"
        ports:
        - containerPort: 7000


---

apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
  - name: web
    protocol: TCP
    port: 7000
    targetPort: 7000
  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
spec:
  selector:
    app: web
  ports:
  - name: web
    protocol: TCP
    port: 7000
    targetPort: 7000
  type: LoadBalancer
